version: '3'
services:
  expenses-tracker-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - expenses-tracker-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://expenses-tracker-db:5432/expenses_tracker
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

  expenses-tracker-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=expenses_tracker
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

